trigger:
- master

pool:
  name: myagent

steps:

# Checkout source code
- checkout: self

# Set JAVA_HOME
- script: |
    export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH

    echo "JAVA_HOME=$JAVA_HOME"
    java -version
    mvn -version
  displayName: 'Verify Java and Maven'

# SonarQube Prepare
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'other'

# Maven Build + SonarQube Analysis
- task: Maven@4
  displayName: 'Build and Analyze'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true

# Publish SonarQube Quality Gate
- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'

# Verify WAR file
- script: |
    echo "Workspace: $(Build.SourcesDirectory)"
    find $(Build.SourcesDirectory) -name "*.war"
  displayName: 'Locate WAR File'

# Publish Artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'sampledemo'
    command: 'build'
    Dockerfile: '**/Dockerfile'

# Deploy to Tomcat (Uncomment when ready)
# - task: TomcatDeployment@1
#   displayName: 'Deploy to Tomcat'
#   inputs:
#     TomcatUrl: 'http://20.235.48.200:8080'
#     Username: 'admin'
#     Password: 'admin123'
#     Warfile: '$(Build.SourcesDirectory)/target/*.war'
#     Context: '/'
#     ServerVersion: '7OrAbove'