trigger:
- master

pool:
  name: myagent

steps:

# Checkout source code
- checkout: self

# Set JAVA_HOME
- script: |
    export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    export PATH=$JAVA_HOME/bin:$PATH

    echo "JAVA_HOME=$JAVA_HOME"
    java -version
    mvn -version
  displayName: 'Verify Java and Maven'

# SonarQube Prepare
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'other'

# Maven Build + SonarQube Analysis
- task: Maven@4
  displayName: 'Build and Analyze'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '/usr/lib/jvm/java-17-openjdk-amd64'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true

# Publish SonarQube Quality Gate
- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'

# Verify WAR file
- script: |
    echo "Workspace: $(Build.SourcesDirectory)"
    find $(Build.SourcesDirectory) -name "*.war"
  displayName: 'Locate WAR File'

# Publish Artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'sampledemo'
    command: 'build'
    Dockerfile: '**/Dockerfile'

- script: |
    trivy image --severity HIGH,CRITICAL sampledemo.azurecr.io/sampledemo:$(Build.BuildId)
  displayName: 'Scan Docker Image with Trivy'

- task: Docker@2
  inputs:
    containerRegistry: 'acr'
    repository: 'sampledemo'
    command: 'push'

- script: |
    docker rm -f sampledemo-green || true

    docker run -d \
      --name sampledemo-green \
      -p 8081:8080 \
      sampledemo.azurecr.io/sampledemo:$(Build.BuildId)
  displayName: 'Deploy Green'

- script: |
    sleep 20
    curl -f http://localhost:8081
  displayName: 'Health Check'

- script: |
    sudo sed -i 's/localhost:8080/localhost:8081/' \
    /etc/nginx/conf.d/sampledemo.conf

    sudo nginx -t
    sudo systemctl reload nginx
  displayName: 'Switch Traffic'

- script: |
    docker stop sampledemo
    docker rm sampledemo
  displayName: 'Remove Old Container'

- script: |
    docker rename sampledemo-green sampledemo
  displayName: 'Promote Green'