trigger:
- master

pool:
  name: myagent

steps:

# Checkout Source
- checkout: self

# SonarQube Preparation
- task: SonarQubePrepare@8
  inputs:
    SonarQube: 'sonarqube'
    scannerMode: 'other'

# Maven Build + SonarQube Analysis
- task: Maven@4
  displayName: 'Build and Analyze'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true

# Publish SonarQube Quality Gate
- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'

# Verify WAR File
- script: |
    echo "Workspace: $(Build.SourcesDirectory)"
    find $(Build.SourcesDirectory) -name "*.war"
  displayName: 'Locate WAR File'

# Publish WAR as Artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# # Deploy to Tomcat
# - task: TomcatDeployment@1
#   displayName: 'Deploy to Tomcat'
#   inputs:
#     TomcatUrl: 'http://20.235.48.200:8080'
#     Username: 'admin'
#     Password: 'admin123'
#     Warfile: '$(Build.SourcesDirectory)/target/*.war'
#     Context: '/'
#     ServerVersion: '7OrAbove'